#!/usr/bin/env bash
# Transfers a file from our client to a server

# Check iif the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Use scp to transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
	echo "File transer successful."
else
	echo "File transer failed."
fi
