#!/usr/bin/env bash
# This script automates the process of installing the `nginx web server`
# on a remote server; Nginx hould be listening on port 80

# -y: Yes - to all prompts so that you won't get any prompts during installation

sudo apt-get -y update				# update the package index
sudo apt-get -y install nginx		# Install Nginx
sudo ufw allow "Nginx HTTP"			# Allow incoming HTTP traffic (port 80) through the Uncomplicated Firewall (ufw) by enabling the predefined "Nginx HTTP" rule.

# Create a custom index file with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart the Nginx service without using systemctl
sudo service nginx stop
sudo service nginx start
