#!/usr/bin/env bash
# This script automates the process of installing an `nginx web server`
# on a remote server - Nginx listens on port 80, and configuring it so
# that `/redirect_me` is redirecting to another page - a youtube page

# -y: Yes - to all prompts so that you won't get any prompts during installation
# sed: Stream editor for filtering and transforming text
# -i: Mofy the file in place
# /server_name _;/a: Specifies an address range for the `sed` command. This matches a line containing `/server_name _;`. The `a` command appends text after the matched line
# location /redirect_me {...}: text to be appended after the matched line


sudo apt-get -y update				# update the package index
sudo apt-get -y install nginx		# Install Nginx
sudo ufw allow "Nginx HTTP"			# Allow incoming HTTP traffic (port 80) through the Uncomplicated Firewall (ufw) by enabling the predefined "Nginx HTTP" rule.

# Create a custom index file with "Hello World!"
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx for URL Rewriting (301 Moved Permanently)
#sudo sed -i '/server_name _;/a \\\n\\tlocation /redirect_me {\\n\\t\\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\\n\\t}' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;}' /etc/nginx/sites-available/default
# Restart the Nginx service without using systemctl
sudo service nginx stop
sudo service nginx start
