#!/usr/bin/env bash
# This script configures an Nginx (web) server to have a custom 404 page
# that contains the string "Ceci n'est pas une page"

# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Configure firewall (ufw)
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable

# Create default HTML page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Configure Nginx for URL Rewriting (301 Moved Permanently)
sudo sed -i "listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Create custom 404 page
sudo sh -c 'echo "Ceci n'est pas une page" > /var/www/html/404.html'

# Configure Nginx for custom 404 page
sudo sed -i '/server_name _;/a \\t\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx stop
sudo service nginx start
