#!/usr/bin/env bash
# This script configures an Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page 

# Update package list
sudo apt-get -y update

# Install the Nginx web server
sudo apt-get -y install nginx

# Configure Uncomplicated firewall (UFW)
sudo ufw enable
sudo ufw allow "Nginx HTTP"	# Opens the necessary ports for Nginx through
chmod -R 755 /var/www	# Set permission for the web directory /var/www

# Create default HTML page
echo "Hello World!" > /var/www/html/index.nginx-debian.html
#echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to have a custom 404 page that contains the string `Ceci n'est pas une page`
new_config=\
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
			root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
		server_name _;
		location / {
			try_files \$uri \$uri/ =404;
		}
		error_page 404 /404.html;
		location /404.html {
			internal;
		}

		if (\$request_filename ~ redirect_me){
			rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
		}
}
"

echo "Ceci n'est pas une page" > /var/www/html/404.html	# Creates a custom 404 page with the content "Ceci n'est pas une page."
echo "$new_config" > /etc/nginx/sites-available/default	# Overwrites the default Nginx server block configuration with the newly defined configuration

# Restart Nginx
sudo service nginx restart
