#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

# Check if the password argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

# MySQL dump configuration
MYSQL_USER="root"
MYSQL_PASSWORD="$1"
MYSQL_DUMP_FILE="backup.sql"
ARCHIVE_NAME="$(date +'%d-%m-%Y').tar.gz"

# Create MySQL dump
mysqldump -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --all-databases > "$MYSQL_DUMP_FILE"

# Create compressed archive
tar -czf "$ARCHIVE_NAME" "$MYSQL_DUMP_FILE"

# Remove the original MySQL dump file
rm "$MYSQL_DUMP_FILE"
