#!/usr/bin/env bash
# Pings an IP address passed as an argument

# Check if an argument is provided
if [ $# -ne 1 ]; then
	#echo "Usage: $0 {IP_ADDRESS}"
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	# Get the IP address from the first argument
	ip_address="$1"

	# Ping the IP address 5 times
	ping -c 5 "$ip_address"
fi
