#!/usr/bin/env bash
# displays a list of currently running processes with hierarchy and user-oriented format.

# Use 'ps' with specific options to display processes.
# -e: Select all processes -for all users, including those which might not have a TTY
# u: Show all processes in a user-oriented format.
# -H: Show process hierarchy (forest).
ps -e u -H
