#!/bin/bash
# displays numbers from 1 to 100, including fizz, buzz and fizzbuzz

for (( i=0; i<100; i=i+1 )); do
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
