#!/usr/bin/env bash
# nested while-loop: displays the time for hours and minutes

hour=0
min=1

while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $min -le 59 ]; do
		echo "$min"
		min=$((min + 1))
	done
	hour=$((hour + 1))
	min=1
done
