#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it's executed on

# Use ifconfig to display all active IPv4 IPs
ifconfig | awk '/inet / {print $2}' | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'
#ip -4 addr show | grep -oP 'inet \K[\d.]+'
