#!/usr/bin/env bash
# Runs the `whoami` command under the user passed as an argument


# Check if an argument is provided
if [ $# -eq 0 ]; then
	echo "usage: $0 <username>"
	exit 1
fi

# Assign the provided username to a variable
username=$1

# Run the `whoami` command under the specified user
sudo -u $username whoami
