#!/usr/bin/env bash
# Configures a container to ensure nginx is running as nginx user
# and nginx is listening on all active IPs on port 8080

# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
	sudo apt update
	sudo apt install nginx -y
fi

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
