#!/usr/bin/env bash
if ! command -v nginx &> /dev/null; then apt update; apt install nginx -y; fi
service nginx stop
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/^listen .*/listen 8080;/g' /etc/nginx/sites-available/default
service nginx start
